"""add questions scouts webhook_events digests challenges

Revision ID: 65551c6e0e28
Revises: 882f11783ed7
Create Date: 2026-09-16 18:59:39.553699

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '65551c6e0e28'
down_revision: str | Sequence[str] | None = '882f11783ed7'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('digests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('profile_version', sa.Integer(), nullable=True),
    sa.Column('question_count', sa.Integer(), nullable=False),
    sa.Column('email_error', sa.Text(), nullable=True),
    sa.Column('email_attempts', sa.SmallInteger(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('generating', 'generated', 'generation_failed', 'empty', 'sending', 'sent', 'send_failed')", name='ck_digests_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_digests_generated_at', 'digests', ['generated_at'], unique=False)
    op.create_table('scouts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('external_scout_id', sa.String(length=128), nullable=True),
    sa.Column('query_text', sa.Text(), nullable=True),
    sa.Column('query_hash', sa.String(length=64), nullable=True),
    sa.Column('sync_status', sa.String(length=16), nullable=False),
    sa.Column('last_sync_error', sa.Text(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('webhook_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('event_id', sa.String(length=128), nullable=False),
    sa.Column('delivery_id', sa.String(length=128), nullable=True),
    sa.Column('attempt', sa.SmallInteger(), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'event_id', name='uq_webhook_events_provider_event')
    )
    op.create_table('questions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('stackoverflow_question_id', sa.BigInteger(), nullable=True),
    sa.Column('canonical_url', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('answer_count', sa.Integer(), nullable=True),
    sa.Column('accepted_answer_id', sa.BigInteger(), nullable=True),
    sa.Column('is_closed', sa.Boolean(), nullable=False),
    sa.Column('is_duplicate', sa.Boolean(), nullable=False),
    sa.Column('question_created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('problem_summary', sa.Text(), nullable=True),
    sa.Column('difficulty', sa.SmallInteger(), nullable=True),
    sa.Column('interesting_reason', sa.Text(), nullable=True),
    sa.Column('enrichment_attempts', sa.SmallInteger(), nullable=False),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('enrichment_error', sa.Text(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('profile_version', sa.Integer(), nullable=True),
    sa.Column('topic_relevance', sa.SmallInteger(), nullable=True),
    sa.Column('technical_depth', sa.SmallInteger(), nullable=True),
    sa.Column('solve_opportunity', sa.SmallInteger(), nullable=True),
    sa.Column('recency_score', sa.SmallInteger(), nullable=True),
    sa.Column('quality_score', sa.SmallInteger(), nullable=True),
    sa.Column('novelty_score', sa.SmallInteger(), nullable=True),
    sa.Column('candidate_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('scored_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('source_event_id', sa.UUID(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('enrichment_pending', 'candidate', 'selected', 'presented', 'solved', 'skipped', 'rejected')", name='ck_questions_status'),
    sa.ForeignKeyConstraint(['source_event_id'], ['webhook_events.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('canonical_url'),
    sa.UniqueConstraint('stackoverflow_question_id')
    )
    op.create_index('idx_questions_next_retry_at', 'questions', ['next_retry_at'], unique=False, postgresql_where=sa.text("status = 'enrichment_pending'"))
    op.create_index('idx_questions_question_created_at', 'questions', ['question_created_at'], unique=False)
    op.create_index('idx_questions_status_score', 'questions', ['status', 'candidate_score'], unique=False)
    op.create_index('idx_questions_tags', 'questions', ['tags'], unique=False, postgresql_using='gin')
    op.create_table('challenges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('digest_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('problem_summary', sa.Text(), nullable=False),
    sa.Column('why_interesting', sa.Text(), nullable=False),
    sa.Column('concepts', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('starting_direction', sa.Text(), nullable=False),
    sa.Column('hints', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('estimated_difficulty', sa.SmallInteger(), nullable=True),
    sa.Column('provider', sa.String(length=32), nullable=True),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('prompt_version', sa.SmallInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['digest_id'], ['digests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('digest_id', 'question_id', name='uq_challenges_digest_question')
    )
    op.create_table('digest_questions',
    sa.Column('digest_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['digest_id'], ['digests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('digest_id', 'question_id'),
    sa.UniqueConstraint('digest_id', 'position', name='uq_digest_questions_position')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('digest_questions')
    op.drop_table('challenges')
    op.drop_index('idx_questions_tags', table_name='questions', postgresql_using='gin')
    op.drop_index('idx_questions_status_score', table_name='questions')
    op.drop_index('idx_questions_question_created_at', table_name='questions')
    op.drop_index('idx_questions_next_retry_at', table_name='questions', postgresql_where=sa.text("status = 'enrichment_pending'"))
    op.drop_table('questions')
    op.drop_table('webhook_events')
    op.drop_table('scouts')
    op.drop_index('idx_digests_generated_at', table_name='digests')
    op.drop_table('digests')
    # ### end Alembic commands ###
